server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka.local:7001/eureka
  instance:
    instance-id: gateway9527
    prefer-ip-address: true 
 
 
zuul: 
  ignored-services: "*"
  routes:
    travelPlan:
      #serviceId: microservicecloud-travel-plan
      path: /myPlan/**
      url: http://travel-plan-api.local:8001
      # http://localhost:9527/myPlan/travelPlan/tim
      # even including swagger
      # http://localhost:9527/myPlan/swagger-ui.html#/
    planSearch:
      #serviceId: microservicecloud-travel-elasticsearch
      path: /mySearch/**
      url: http://travel-plan-elasticsearch.local:8002
      # http://localhost:9527/mySearch/swagger-ui.html#/
    myBuilder:
      #serviceId: microservicecloud-travel-builder
      path: /myBuilder/**
      url: http://travel-automated-builder.local:8003
      # http://localhost:9527/myBuilder/swagger-ui.html#/
 
info:
  app.name: gof-microcloud
  company.name: www.gof.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

